export XLA_PYTHON_CLIENT_ALLOCATOR=platform
export XLA_PYTHON_CLIENT_PREALLOCATE=false
# export CUDA_VISIBLE_DEVICES='1'

python -m EasyLM.models.gemmapro.gemmapro_train \
--load_checkpoint=flax_params::/Users/junpark/Downloads/flax_model_pro.msgpack \
--mesh_dim=1,1,1 \
--dtype=bf16 \
--total_steps=4 \
--log_freq=1 \
--save_model_freq=4 \
--save_milestone_freq=4 \
--train_dataset.type='huggingface' \
--train_dataset.text_processor.fields='text' \
--train_dataset.huggingface_dataset.path='gemmathon/merged-pb-kw-nw' \
--train_dataset.huggingface_dataset.name='default' \
--train_dataset.huggingface_dataset.seq_length=8192 \
--train_dataset.huggingface_dataset.batch_size=1 \
--train_dataset.huggingface_dataset.streaming=True \
--optimizer.type=adamw \
--optimizer.adamw_optimizer.multiply_by_parameter_scale=True \
--optimizer.adamw_optimizer.weight_decay=0.1 \
--optimizer.adamw_optimizer.lr=0.2 \
--optimizer.adamw_optimizer.end_lr=0.1 \
--optimizer.adamw_optimizer.lr_warmup_steps=0 \
--checkpointer.save_optimizer_state=True \
--checkpointer.float_dtype=bf16 \
--logger.online=False \
--logger.output_dir=./gemma-checkpoint
